CREATE TABLE Blog (
	blogId				VARCHAR(256)	NOT NULL CONSTRAINT Blog_PK PRIMARY KEY,
	userId				VARCHAR(256)	NOT NULL,
	url					VARCHAR(256)	NOT NULL,
	title				VARCHAR(256)	NOT NULL,
	description			VARCHAR(256)	NOT NULL
);

CREATE TABLE Author (
	userId				VARCHAR(256)	NOT NULL CONSTRAINT Author_PK PRIMARY KEY,
	name				VARCHAR(256)	NOT NULL,
	url					VARCHAR(256)	NOT NULL,
	email				VARCHAR(256),
	avatar				VARCHAR(256)
);

CREATE TABLE Entry (
	entryId				BIGINT			NOT NULL GENERATED ALWAYS AS IDENTITY CONSTRAINT Entry_PK PRIMARY KEY,
	blogId				VARCHAR(256)	NOT NULL,
	title				VARCHAR(256)	NOT NULL,
	postId				BIGINT			NOT NULL,
	tags				VARCHAR(256)    NOT NULL 
);

CREATE TABLE Post (
	postId				BIGINT			NOT NULL GENERATED ALWAYS AS IDENTITY CONSTRAINT Post_PK PRIMARY KEY,
	userId				VARCHAR(256)	NOT NULL,
	content				LONG VARCHAR	NOT NULL,
	creation			DATE			NOT NULL
);

CREATE TABLE Comment (
	commentId			INTEGER			NOT NULL GENERATED ALWAYS AS IDENTITY CONSTRAINT Comment_PK PRIMARY KEY,
	entryId				BIGINT			NOT NULL,
	postId				BIGINT			NOT NULL
)
